### ISSUE TITLE
When correcting a line zoom out the image to have the whole line visible

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#23]
This is a bug: 

When editing lines of text, sometimes the image is zoomed so I can see the whole line. Most of the time though, when I am editing a line, I do not see the whole line just about 80-90% of it. When I move the image to see the whole line and jump back to text, the line resets to the previous (unwanted) position. Please correct this to keep the whole line visible.

**Comment by zabak** [comment]
I just figured out what are the height and pad values are for (not intuitive). Anyway, the request stands. When I click on the line in image or in the text that line should be visible as a whole.

**Comment by zabak** [comment]
The Height and Pad fields did not solve the problem completely. Their default values are such that when I click on some lines I still see just part of the line on the image:
![image](https://user-images.githubusercontent.com/811537/89548793-c2099500-d807-11ea-8e1c-d6d2175ff7eb.png)
and I still need to zoom out a bit to see the whole line
![image](https://user-images.githubusercontent.com/811537/89548865-e06f9080-d807-11ea-81a7-fceda7887c13.png)

**Comment by michal-hradis** [comment]
The viewer now keeps zoom when switching between text lines. If the textline does not fit onto the screen, the view moves left and right with your position in the text field.
