### ISSUE TITLE
Try to follow the order of the lines on page when correcting

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#24]
It is much easier to correct consequent lines of text, because nothing breaks the flow. If the lines are mixed up randomly you have to read i bit of text on the line before and after on the image to get the context of the line being edited.

**Comment by michal-hradis** [comment]
Previously, we did not have reading order of paragraphs from the Layout Analysis. Now, paragraphs are ordered - it is not perfect. Paragraph order can be changed in layout mode. I hope the issue is solved.
