### ISSUE TITLE
When I successfully add a new collaborator the name remains in the form field

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#31]
After adding a new collaborator, I would expect I will see a list of existing collaborators and an empty form. When I add a new collaborator, I see a message that the collaborator has been added successfully and below that if the form with the collaborator name in it. This is very confusing. Does it mean thet whoever is in the form has access? Does re-sending an empty form mean I have removed all collaborators?

**Comment by michal-hradis** [comment]
And please remove "client client".

**Comment by michal-hradis** [comment]
Yes, you see a list of "active" collaborators. You can add and remove collaborators from this list. The "Submit" button stores the list of the collaborators. Yes, "Submitting" empty list of collaborators removes all collaborators.

It is not "Add collaborators" form. It is "Edit collaborators" form.

I expect we will not change this behavior as it is mostly consistent with other application (e.g. google drive).

**Comment by zabak** [comment]
OK, just please remove that intrusive client client :-)

**Comment by LachubCz** [comment]
I removed client@client.cz appearence in petr branch. Changes will take effect soon after I merge it with master.
