### ISSUE TITLE
Use different font for text corrections

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#32]
![image](https://user-images.githubusercontent.com/811537/81809721-17dce280-9522-11ea-83d3-b8abd43d23ac.png)

It is impossible to distinguish between I and l in Arial font. Please change it to Times New Roman or something similar.

**Comment by LachubCz** [comment]
Verdana is now set as the prefered font in petr branch. Changes will take effect soon after I merge it with master.
