### ISSUE TITLE
layout displayed in leaflet does not match the page

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#34]
![image](https://user-images.githubusercontent.com/811537/81819768-0a2e5980-9530-11ea-93fb-07d06817e1af.png)
https://pero-ocr.fit.vutbr.cz/layout_analysis/show_results/38a7cfa6-5da6-4d6c-a840-b2d5a6563fe3

**Comment by michal-hradis** [comment]
We have updated layout editor code. Could you check if this problem persists?

**Comment by zabak** [comment]
well... I see no change in chrome so I tested Firefox and Safari and the result is that the preview page is still too wide and in Leaflet it is turned 90 degrees (it probably ignores the image orientation info in the jpg file). 

![image](https://user-images.githubusercontent.com/811537/82316290-e0ac7c80-99cc-11ea-9450-8deb94c88f3a.png)

**Comment by zabak** [comment]
The first page is incorrectly displayed too wide. Both pages are turned 90°in Leaflet

**Comment by michal-hradis** [comment]
We fixed already uploaded images. The live app should show all images correctly. If you see some rotated pages, update your browser :).
