### ISSUE TITLE
When layout analysis is being run the buttons do not fit on one line

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#42]
![image](https://user-images.githubusercontent.com/811537/84208648-80cd6100-aab4-11ea-8dad-8a1cee25cb6c.png)

**Comment by michal-hradis** [comment]
In general, the buttons do not fit on single line. This depends on the table width. Document table now contains page previews and all rows are taller. I consider this issue irrelevant at this time.
