### ISSUE TITLE
When I delete an image right after uploading, it's metadata remain

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#44]
I uploaded two images, reloaded the upload screen, deleted one of them by clicking remove image, then I ran layout analysis. I ended up with an image and a "ghost" of the deleted image. This "ghost" disappears after OCR is run.

![image](https://user-images.githubusercontent.com/811537/84209178-c3436d80-aab5-11ea-85a0-a081946fe1d9.png)

**Comment by LachubCz** [comment]
This bug is now fixed in petr branch. Changes will take effect soon after I merge it with master.
