### ISSUE TITLE
Fix routes /layout_analysis/get_image_result/<string:image_id> and /layout_analysis/get_result_preview/<string:image_id>

### ISSUE THREAD

**Issue by kohuthonza** [DCGM/pero_ocr_web#50]
get_image_by_id(image_id) returns NoneType when the image deleted flag is set to 1. Routes need to be fixed, so they work with deleted images.

**Comment by kohuthonza** [comment]
Generally we need to find every route that is dealing with image_id (getting image by image_id) and check that the image that exists and is not deleted.

**Comment by xkissm00** [comment]
Fixed /layout_analysis/get_result_preview/<string:image_id>
