### ISSUE TITLE
Put newly created documents at the top of the list in document browser

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#54]
Add a column with the date of last action and make it default after creating a new document of otherwise show the newly created document at the top of the list. I currently have more than one page of documents and a new one appears on the second page so it is difficult to find. I will add something more about the dates in a new issue.

Other option: after creating a new document go directly to Upload images page. 

Both options would be good.

**Comment by zabak** [comment]
We are close but not there yet. What I need is to have the document I am currently working with at the top. The default is (I guess) to have my documents first and sorted oldest first. I need newest first. The problem is there is no date column (creation date, last change date). The problem is the sort setting is not stored anywhere so it is lost when I reload a page. Why do I need to reload a page? Because that is the only way to see if my job is finished. But I have so many documents that the newest one is on page 2. Clicking reload puts me back on page 1 with default sorting so I have to search for my document again after each reload to see if it is finished.

**Comment by michal-hradis** [comment]
We will probably add creation date, last change date.

**Comment by michal-hradis** [comment]
Document ordering works. Ordering by "Page" actually orders documents by creation date. This is default. Otherwise sorting and filtering is persistent. I did not want to add an additional column. (this was quite an old update)
