### ISSUE TITLE
Multipage file support

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#61]
I tried to do ocr of a multipage PNG (or animated png) converted from pdf. Did not work as expected (or: As expected, did not work :)

https://pero-ocr.fit.vutbr.cz/ocr/show_results/4ed857d9-88ca-4958-8a2f-6fa78391d8c4

**Comment by michal-hradis** [comment]
Multipage PNG, GIF and similar files will not be supported.

**Comment by michal-hradis** [comment]
Multipage PNG, GIF and similar files will not be supported.
