### ISSUE TITLE
API for the upload of images for processing

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#70]
Create an API which would allow upload of a list of images into PERO web version from another system (ProArc or other digitisation software).

Use case: user digitizes a book. They do OCR of all pages via the API. The user then uploads images and OCR into a digitisation workflow system (ProArc). The user then decides to correct/improve the OCR of some pages through PERO web interface. The digitisation system then batch uploads selected page images to pero web and redirects the user to that document on PERO OCR web app. After the user finishes his changes, he returns to ProArc and initiates download of the new OCR for those pages. Previous OCR files for those pages are replaced.

API requirements: 
- uses special login credentials (different for each Proarc installation)
- accepts e-mail of the operator (=username of the operator in the PERO OCR web) 
- optionally - id of the document
- and one or more image files 
- and (optionally, perhaps later) specification of layout analysis, baseline detector, OCR and language model to use. 

Returns PERO id of the document.

**Comment by michal-hradis** [comment]
Done. Implemented in 912b25d43dde04065d5e1b27514739a85968a0f6.
