### ISSUE TITLE
Batch download of ALTO and TXT

### ISSUE THREAD

**Issue by zabak** [DCGM/pero_ocr_web#71]
To finish what we started in #70, there should be a way to automatically download the finished OCR (ALTO and TXT) for all pages. If the OCR is not available (not finished etc.) it should return an error or rather a status message (something like "OCR is not finished yet"). Or perhaps have a separate status API call and separate download?

**Comment by michal-hradis** [comment]
Implemented for API access in 912b25d43dde04065d5e1b27514739a85968a0f6. The download calls do no check state of the document when exporting text and PAGE. ALTO returns with error code if OCR is not available. I don't think that this check is needed as we can't check for "manual correction DONE", anyway.

**Comment by michal-hradis** [comment]
Bulk ALTO download for normal users (NON API) can be done by script /user_scripts/download_document.py
